"""Markdown rendering for the release code-quality inventory."""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any


def render_markdown(report: dict[str, Any]) -> str:
    lines = _summary_lines(report["summary"])
    _append_oversized_files(lines, report["oversized_files"])
    _append_duplicate_groups(lines, report["duplicate_function_groups"])
    _append_function_table(
        lines,
        title="Python functions at least 100 lines",
        headers=("Lines", "Complexity", "Function"),
        rows=((item["lines"], item["complexity"], f"`{item['identity']}`") for item in report["long_functions"]),
    )
    _append_function_table(
        lines,
        title="Python functions at complexity 30+",
        headers=("Complexity", "Lines", "Function"),
        rows=((item["complexity"], item["lines"], f"`{item['identity']}`") for item in report["complex_functions"]),
    )
    _append_silent_handlers(lines, report["silent_broad_exception_handlers"])
    if report["forbidden_residue"]:
        lines.extend(["", "## Forbidden one-shot delivery residue", ""])
        lines.extend(f"- `{path}`" for path in report["forbidden_residue"])
    return "\n".join(lines).rstrip() + "\n"


def _summary_lines(summary: dict[str, Any]) -> list[str]:
    lines = [
        "# HOL Guard release/3.0 code-quality audit",
        "",
        (
            "This inventory is generated by `scripts/ci/code_quality_audit.py`. "
            "It records structural debt without treating a large file or complex "
            "function as proof of a bug."
        ),
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "| --- | ---: |",
    ]
    labels = (
        ("Code/config files scanned", "code_files"),
        ("Files over 500 lines", "oversized_files"),
        ("Handwritten files over 500 lines", "oversized_handwritten_files"),
        ("Generated files over 500 lines", "oversized_generated_files"),
        ("Production/tooling Python functions", "python_functions"),
        ("Python functions at least 100 lines", "long_python_functions"),
        ("Python functions at complexity 30+", "high_complexity_python_functions"),
        ("Exact Python function-copy groups", "duplicate_function_groups"),
        ("Functions in exact-copy groups", "duplicate_function_instances"),
        ("Silent broad exception handlers", "silent_broad_exception_handlers"),
        ("Forbidden one-shot delivery artifacts", "forbidden_residue"),
    )
    lines.extend(f"| {label} | {summary[key]} |" for label, key in labels)
    return lines


def _append_oversized_files(lines: list[str], items: list[dict[str, Any]]) -> None:
    lines.extend(
        [
            "",
            "## Files over 500 lines",
            "",
            "| Lines | Category | Generated | Path |",
            "| ---: | --- | --- | --- |",
        ]
    )
    lines.extend(
        (f"| {item['lines']} | {item['category']} | {'yes' if item['generated'] else 'no'} | `{item['path']}` |")
        for item in items
    )


def _append_duplicate_groups(lines: list[str], groups: list[dict[str, Any]]) -> None:
    lines.extend(["", "## Exact Python function-copy groups", ""])
    for index, group in enumerate(groups, start=1):
        lines.append(f"### Group {index}: {group['lines']} lines, {len(group['instances'])} instances")
        lines.append("")
        for item in group["instances"]:
            lines.append(f"- `{item['path']}:{item['line']}` `{item['qualname']}`")
        lines.append("")


def _append_function_table(
    lines: list[str],
    *,
    title: str,
    headers: tuple[str, str, str],
    rows: Iterable[tuple[object, object, object]],
) -> None:
    first, second, third = headers
    lines.extend(
        [
            "",
            f"## {title}",
            "",
            f"| {first} | {second} | {third} |",
            "| ---: | ---: | --- |",
        ]
    )
    lines.extend(
        f"| {first_value} | {second_value} | {third_value} |" for first_value, second_value, third_value in rows
    )


def _append_silent_handlers(lines: list[str], items: list[dict[str, Any]]) -> None:
    lines.extend(
        [
            "",
            "## Silent broad exception handlers",
            "",
            (
                "These require review before modification because many are deliberate "
                "fail-safe or best-effort boundaries."
            ),
            "",
            "| Exception | Location | Function |",
            "| --- | --- | --- |",
        ]
    )
    lines.extend(
        f"| `{item['exception']}` | `{item['path']}:{item['line']}` | `{item['qualname']}` |" for item in items
    )


__all__ = ["render_markdown"]
